planilla:
    data:
        porcentaje:
            retencion: 0.13
        rango:
            variacion:
                kilogramos: {{0.0, 8.0}, {9.0, 25.0} , {26.0, 45.0}, {46.0, Double.MAX_VALUE}}
                grasa: {{0.0, 15.0}, {16.0, 25.0}, {26.0, 40.0}, {41.0, Double.MAX_VALUE}}
                solidos: {{0.0, 6.0}, {7.0, 12.0}, {13.0, 35.0}, {36.0, Double.MAX_VALUE}}
            grasa: {{0.0, 20.0}, {21.0, 45.0}, {46.0, Double.MAX_VALUE}}
            solidos: {{0.0, 7.0}, {8.0, 18.0}, {19.0, 35.0}, {36.0, Double.MAX_VALUE}}
        descuentos:
            kilogramos: {0.0, 7.0, 15.0, 30.0}
            grasa: {0.0, 12.0, 20.0, 30.0}
            solidos: {0.0, 18.0, 27.0, 45.0}
        proveedor:
            categorias: {"A","B","C","D"}
        pagos:
            kilogramos: {700.0, 550.0, 400.0, 250.0}
            grasa: {30.0, 80.0, 120.0}
            solidos: {-130.0, -90.0, 95.0, 150.0}
        bonificaciones:
            frecuencia: {0.2, 0.12, 0.08}


